# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model_orchestrator.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18model_orchestrator.proto\x12\x12model_orchestrator\"\"\n\x12ProcessTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"%\n\x13ProcessTextResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"(\n\x18GenerateEmbeddingRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\".\n\x19GenerateEmbeddingResponse\x12\x11\n\tembedding\x18\x01 \x03(\x02\":\n\x10LoadModelRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x12\n\nmodel_path\x18\x02 \x01(\t\"$\n\x11LoadModelResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"(\n\x12UnloadModelRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\"&\n\x13UnloadModelResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\">\n\x14GetPredictionRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x12\n\ninput_data\x18\x02 \x01(\t\"+\n\x15GetPredictionResponse\x12\x12\n\nprediction\x18\x01 \x01(\t2\x8f\x04\n\x11ModelOrchestrator\x12`\n\x0bProcessText\x12&.model_orchestrator.ProcessTextRequest\x1a\'.model_orchestrator.ProcessTextResponse\"\x00\x12r\n\x11GenerateEmbedding\x12,.model_orchestrator.GenerateEmbeddingRequest\x1a-.model_orchestrator.GenerateEmbeddingResponse\"\x00\x12Z\n\tLoadModel\x12$.model_orchestrator.LoadModelRequest\x1a%.model_orchestrator.LoadModelResponse\"\x00\x12`\n\x0bUnloadModel\x12&.model_orchestrator.UnloadModelRequest\x1a\'.model_orchestrator.UnloadModelResponse\"\x00\x12\x66\n\rGetPrediction\x12(.model_orchestrator.GetPredictionRequest\x1a).model_orchestrator.GetPredictionResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_orchestrator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROCESSTEXTREQUEST']._serialized_start=48
  _globals['_PROCESSTEXTREQUEST']._serialized_end=82
  _globals['_PROCESSTEXTRESPONSE']._serialized_start=84
  _globals['_PROCESSTEXTRESPONSE']._serialized_end=121
  _globals['_GENERATEEMBEDDINGREQUEST']._serialized_start=123
  _globals['_GENERATEEMBEDDINGREQUEST']._serialized_end=163
  _globals['_GENERATEEMBEDDINGRESPONSE']._serialized_start=165
  _globals['_GENERATEEMBEDDINGRESPONSE']._serialized_end=211
  _globals['_LOADMODELREQUEST']._serialized_start=213
  _globals['_LOADMODELREQUEST']._serialized_end=271
  _globals['_LOADMODELRESPONSE']._serialized_start=273
  _globals['_LOADMODELRESPONSE']._serialized_end=309
  _globals['_UNLOADMODELREQUEST']._serialized_start=311
  _globals['_UNLOADMODELREQUEST']._serialized_end=351
  _globals['_UNLOADMODELRESPONSE']._serialized_start=353
  _globals['_UNLOADMODELRESPONSE']._serialized_end=391
  _globals['_GETPREDICTIONREQUEST']._serialized_start=393
  _globals['_GETPREDICTIONREQUEST']._serialized_end=455
  _globals['_GETPREDICTIONRESPONSE']._serialized_start=457
  _globals['_GETPREDICTIONRESPONSE']._serialized_end=500
  _globals['_MODELORCHESTRATOR']._serialized_start=503
  _globals['_MODELORCHESTRATOR']._serialized_end=1030
# @@protoc_insertion_point(module_scope)
