# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: note_manager.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12note_manager.proto\x12\x0cnote_manager\"$\n\x11\x43reateNoteRequest\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\"%\n\x12\x43reateNoteResponse\x12\x0f\n\x07note_id\x18\x01 \x01(\t\"5\n\x11UpdateNoteRequest\x12\x0f\n\x07note_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"%\n\x12UpdateNoteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"$\n\x11\x44\x65leteNoteRequest\x12\x0f\n\x07note_id\x18\x01 \x01(\t\"%\n\x12\x44\x65leteNoteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"!\n\x0eGetNoteRequest\x12\x0f\n\x07note_id\x18\x01 \x01(\t\"\"\n\x0fGetNoteResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\"\x12\n\x10ListNotesRequest\"%\n\x11ListNotesResponse\x12\x10\n\x08note_ids\x18\x01 \x03(\t\"(\n\x14ParseMarkdownRequest\x12\x10\n\x08markdown\x18\x01 \x01(\t\"3\n\x15ParseMarkdownResponse\x12\x1a\n\x12structured_content\x18\x01 \x01(\t\"/\n\x11ToMarkdownRequest\x12\x1a\n\x12structured_content\x18\x01 \x01(\t\"&\n\x12ToMarkdownResponse\x12\x10\n\x08markdown\x18\x01 \x01(\t2\xcf\x04\n\x0bNoteManager\x12Q\n\nCreateNote\x12\x1f.note_manager.CreateNoteRequest\x1a .note_manager.CreateNoteResponse\"\x00\x12Q\n\nUpdateNote\x12\x1f.note_manager.UpdateNoteRequest\x1a .note_manager.UpdateNoteResponse\"\x00\x12Q\n\nDeleteNote\x12\x1f.note_manager.DeleteNoteRequest\x1a .note_manager.DeleteNoteResponse\"\x00\x12H\n\x07GetNote\x12\x1c.note_manager.GetNoteRequest\x1a\x1d.note_manager.GetNoteResponse\"\x00\x12N\n\tListNotes\x12\x1e.note_manager.ListNotesRequest\x1a\x1f.note_manager.ListNotesResponse\"\x00\x12Z\n\rParseMarkdown\x12\".note_manager.ParseMarkdownRequest\x1a#.note_manager.ParseMarkdownResponse\"\x00\x12Q\n\nToMarkdown\x12\x1f.note_manager.ToMarkdownRequest\x1a .note_manager.ToMarkdownResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'note_manager_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATENOTEREQUEST']._serialized_start=36
  _globals['_CREATENOTEREQUEST']._serialized_end=72
  _globals['_CREATENOTERESPONSE']._serialized_start=74
  _globals['_CREATENOTERESPONSE']._serialized_end=111
  _globals['_UPDATENOTEREQUEST']._serialized_start=113
  _globals['_UPDATENOTEREQUEST']._serialized_end=166
  _globals['_UPDATENOTERESPONSE']._serialized_start=168
  _globals['_UPDATENOTERESPONSE']._serialized_end=205
  _globals['_DELETENOTEREQUEST']._serialized_start=207
  _globals['_DELETENOTEREQUEST']._serialized_end=243
  _globals['_DELETENOTERESPONSE']._serialized_start=245
  _globals['_DELETENOTERESPONSE']._serialized_end=282
  _globals['_GETNOTEREQUEST']._serialized_start=284
  _globals['_GETNOTEREQUEST']._serialized_end=317
  _globals['_GETNOTERESPONSE']._serialized_start=319
  _globals['_GETNOTERESPONSE']._serialized_end=353
  _globals['_LISTNOTESREQUEST']._serialized_start=355
  _globals['_LISTNOTESREQUEST']._serialized_end=373
  _globals['_LISTNOTESRESPONSE']._serialized_start=375
  _globals['_LISTNOTESRESPONSE']._serialized_end=412
  _globals['_PARSEMARKDOWNREQUEST']._serialized_start=414
  _globals['_PARSEMARKDOWNREQUEST']._serialized_end=454
  _globals['_PARSEMARKDOWNRESPONSE']._serialized_start=456
  _globals['_PARSEMARKDOWNRESPONSE']._serialized_end=507
  _globals['_TOMARKDOWNREQUEST']._serialized_start=509
  _globals['_TOMARKDOWNREQUEST']._serialized_end=556
  _globals['_TOMARKDOWNRESPONSE']._serialized_start=558
  _globals['_TOMARKDOWNRESPONSE']._serialized_end=596
  _globals['_NOTEMANAGER']._serialized_start=599
  _globals['_NOTEMANAGER']._serialized_end=1190
# @@protoc_insertion_point(module_scope)
