# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import note_manager_pb2 as note__manager__pb2

GRPC_GENERATED_VERSION = '1.65.4'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in note_manager_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class NoteManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateNote = channel.unary_unary(
                '/note_manager.NoteManager/CreateNote',
                request_serializer=note__manager__pb2.CreateNoteRequest.SerializeToString,
                response_deserializer=note__manager__pb2.CreateNoteResponse.FromString,
                _registered_method=True)
        self.UpdateNote = channel.unary_unary(
                '/note_manager.NoteManager/UpdateNote',
                request_serializer=note__manager__pb2.UpdateNoteRequest.SerializeToString,
                response_deserializer=note__manager__pb2.UpdateNoteResponse.FromString,
                _registered_method=True)
        self.DeleteNote = channel.unary_unary(
                '/note_manager.NoteManager/DeleteNote',
                request_serializer=note__manager__pb2.DeleteNoteRequest.SerializeToString,
                response_deserializer=note__manager__pb2.DeleteNoteResponse.FromString,
                _registered_method=True)
        self.GetNote = channel.unary_unary(
                '/note_manager.NoteManager/GetNote',
                request_serializer=note__manager__pb2.GetNoteRequest.SerializeToString,
                response_deserializer=note__manager__pb2.GetNoteResponse.FromString,
                _registered_method=True)
        self.ListNotes = channel.unary_unary(
                '/note_manager.NoteManager/ListNotes',
                request_serializer=note__manager__pb2.ListNotesRequest.SerializeToString,
                response_deserializer=note__manager__pb2.ListNotesResponse.FromString,
                _registered_method=True)
        self.ParseMarkdown = channel.unary_unary(
                '/note_manager.NoteManager/ParseMarkdown',
                request_serializer=note__manager__pb2.ParseMarkdownRequest.SerializeToString,
                response_deserializer=note__manager__pb2.ParseMarkdownResponse.FromString,
                _registered_method=True)
        self.ToMarkdown = channel.unary_unary(
                '/note_manager.NoteManager/ToMarkdown',
                request_serializer=note__manager__pb2.ToMarkdownRequest.SerializeToString,
                response_deserializer=note__manager__pb2.ToMarkdownResponse.FromString,
                _registered_method=True)


class NoteManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateNote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateNote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteNote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListNotes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ParseMarkdown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ToMarkdown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NoteManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateNote': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateNote,
                    request_deserializer=note__manager__pb2.CreateNoteRequest.FromString,
                    response_serializer=note__manager__pb2.CreateNoteResponse.SerializeToString,
            ),
            'UpdateNote': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateNote,
                    request_deserializer=note__manager__pb2.UpdateNoteRequest.FromString,
                    response_serializer=note__manager__pb2.UpdateNoteResponse.SerializeToString,
            ),
            'DeleteNote': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteNote,
                    request_deserializer=note__manager__pb2.DeleteNoteRequest.FromString,
                    response_serializer=note__manager__pb2.DeleteNoteResponse.SerializeToString,
            ),
            'GetNote': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNote,
                    request_deserializer=note__manager__pb2.GetNoteRequest.FromString,
                    response_serializer=note__manager__pb2.GetNoteResponse.SerializeToString,
            ),
            'ListNotes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListNotes,
                    request_deserializer=note__manager__pb2.ListNotesRequest.FromString,
                    response_serializer=note__manager__pb2.ListNotesResponse.SerializeToString,
            ),
            'ParseMarkdown': grpc.unary_unary_rpc_method_handler(
                    servicer.ParseMarkdown,
                    request_deserializer=note__manager__pb2.ParseMarkdownRequest.FromString,
                    response_serializer=note__manager__pb2.ParseMarkdownResponse.SerializeToString,
            ),
            'ToMarkdown': grpc.unary_unary_rpc_method_handler(
                    servicer.ToMarkdown,
                    request_deserializer=note__manager__pb2.ToMarkdownRequest.FromString,
                    response_serializer=note__manager__pb2.ToMarkdownResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'note_manager.NoteManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('note_manager.NoteManager', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NoteManager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateNote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/note_manager.NoteManager/CreateNote',
            note__manager__pb2.CreateNoteRequest.SerializeToString,
            note__manager__pb2.CreateNoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateNote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/note_manager.NoteManager/UpdateNote',
            note__manager__pb2.UpdateNoteRequest.SerializeToString,
            note__manager__pb2.UpdateNoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteNote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/note_manager.NoteManager/DeleteNote',
            note__manager__pb2.DeleteNoteRequest.SerializeToString,
            note__manager__pb2.DeleteNoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/note_manager.NoteManager/GetNote',
            note__manager__pb2.GetNoteRequest.SerializeToString,
            note__manager__pb2.GetNoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListNotes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/note_manager.NoteManager/ListNotes',
            note__manager__pb2.ListNotesRequest.SerializeToString,
            note__manager__pb2.ListNotesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ParseMarkdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/note_manager.NoteManager/ParseMarkdown',
            note__manager__pb2.ParseMarkdownRequest.SerializeToString,
            note__manager__pb2.ParseMarkdownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ToMarkdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/note_manager.NoteManager/ToMarkdown',
            note__manager__pb2.ToMarkdownRequest.SerializeToString,
            note__manager__pb2.ToMarkdownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
