# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: voice_processor.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15voice_processor.proto\x12\x0fvoice_processor\"\'\n\x16RecognizeSpeechRequest\x12\r\n\x05\x61udio\x18\x01 \x01(\x0c\"\'\n\x17RecognizeSpeechResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\"\'\n\x17SynthesizeSpeechRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\")\n\x18SynthesizeSpeechResponse\x12\r\n\x05\x61udio\x18\x01 \x01(\x0c\x32\xe3\x01\n\x0eVoiceProcessor\x12\x66\n\x0fRecognizeSpeech\x12\'.voice_processor.RecognizeSpeechRequest\x1a(.voice_processor.RecognizeSpeechResponse\"\x00\x12i\n\x10SynthesizeSpeech\x12(.voice_processor.SynthesizeSpeechRequest\x1a).voice_processor.SynthesizeSpeechResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'voice_processor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RECOGNIZESPEECHREQUEST']._serialized_start=42
  _globals['_RECOGNIZESPEECHREQUEST']._serialized_end=81
  _globals['_RECOGNIZESPEECHRESPONSE']._serialized_start=83
  _globals['_RECOGNIZESPEECHRESPONSE']._serialized_start=83
  _globals['_RECOGNIZESPEECHRESPONSE']._serialized_end=122
  _globals['_SYNTHESIZESPEECHREQUEST']._serialized_start=124
  _globals['_SYNTHESIZESPEECHREQUEST']._serialized_end=163
  _globals['_SYNTHESIZESPEECHRESPONSE']._serialized_start=165
  _globals['_SYNTHESIZESPEECHRESPONSE']._serialized_end=206
  _globals['_VOICEPROCESSOR']._serialized_start=209
  _globals['_VOICEPROCESSOR']._serialized_end=436
# @@protoc_insertion_point(module_scope)
