# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import voice_processor_pb2 as voice__processor__pb2

GRPC_GENERATED_VERSION = '1.65.4'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in voice_processor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class VoiceProcessorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RecognizeSpeech = channel.unary_unary(
                '/voice_processor.VoiceProcessor/RecognizeSpeech',
                request_serializer=voice__processor__pb2.RecognizeSpeechRequest.SerializeToString,
                response_deserializer=voice__processor__pb2.RecognizeSpeechResponse.FromString,
                _registered_method=True)
        self.SynthesizeSpeech = channel.unary_unary(
                '/voice_processor.VoiceProcessor/SynthesizeSpeech',
                request_serializer=voice__processor__pb2.SynthesizeSpeechRequest.SerializeToString,
                response_deserializer=voice__processor__pb2.SynthesizeSpeechResponse.FromString,
                _registered_method=True)


class VoiceProcessorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RecognizeSpeech(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SynthesizeSpeech(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VoiceProcessorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RecognizeSpeech': grpc.unary_unary_rpc_method_handler(
                    servicer.RecognizeSpeech,
                    request_deserializer=voice__processor__pb2.RecognizeSpeechRequest.FromString,
                    response_serializer=voice__processor__pb2.RecognizeSpeechResponse.SerializeToString,
            ),
            'SynthesizeSpeech': grpc.unary_unary_rpc_method_handler(
                    servicer.SynthesizeSpeech,
                    request_deserializer=voice__processor__pb2.SynthesizeSpeechRequest.FromString,
                    response_serializer=voice__processor__pb2.SynthesizeSpeechResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'voice_processor.VoiceProcessor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('voice_processor.VoiceProcessor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VoiceProcessor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RecognizeSpeech(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/voice_processor.VoiceProcessor/RecognizeSpeech',
            voice__processor__pb2.RecognizeSpeechRequest.SerializeToString,
            voice__processor__pb2.RecognizeSpeechResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SynthesizeSpeech(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/voice_processor.VoiceProcessor/SynthesizeSpeech',
            voice__processor__pb2.SynthesizeSpeechRequest.SerializeToString,
            voice__processor__pb2.SynthesizeSpeechResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
